### =========================
### REGISTER
### =========================
### register (正常)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "double@example.com",
  "password": "password123",
  "prefecture": "大阪府"
}
### register（未入力エラー）
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "",
  "email": "",
  "password": "",
  "prefecture": ""
}
### register（メール形式エラー）
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "testexample.com",
  "password": "password123",
  "prefecture": "大阪府"
}
### register（重複エラー）
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@example.com",
  "password": "password123",
  "prefecture": "大阪府"
}


### =========================
### LOGIN
### =========================
### login (正常)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### login（未入力）
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### login（メール形式エラー）
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testexample.com",
  "password": "password123"
}

### login（ユーザー存在しない）
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "nouser@example.com",
  "password": "password123"
}

### login（パスワード違い）
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "wrongpassword"
}