@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6ImRvdWJsZUBleGFtcGxlLmNvbSIsImlhdCI6MTc3NjUxMTgzOCwiZXhwIjoxNzc2NTE1NDM4fQ.9XcOaMArYLa_AVFiauO7eIPf75GiUD33iHWyA12L-uA
### =========================
### POST /reservations(予約登録)
### =========================

### 正常
POST http://localhost:3000/api/reservations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "room_id": 119,
  "check_in": "2026-05-29",
  "check_out": "2026-05-30",
  "guest_count": 2
}

### 重複予約（409）
POST http://localhost:3000/api/reservations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "room_id": 21,
  "check_in": "2026-05-10",
  "check_out": "2026-05-12",
  "guest_count": 1
}

### 定員超過（400）
POST http://localhost:3000/api/reservations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "room_id": 24,
  "check_in": "2026-05-20",
  "check_out": "2026-05-22",
  "guest_count": 3
}

### =========================
### GET /reservatoins (予約一覧取得)
### =========================
### 予約一覧取得
GET http://localhost:3000/api/reservations
Authorization: Bearer {{token}}

### =========================
### GET /reservatoins/[reservationId] (予約詳細取得)
### =========================
### 予約詳細取得
GET http://localhost:3000/api/reservations/58
Authorization: Bearer {{token}}

### =========================
### PATCH /reservations/[reservationId]/cancel(予約キャンセル)
### =========================
### 予約キャンセル
PATCH http://localhost:3000/api/reservations/58/cancel
Authorization: Bearer {{token}}

### すでにキャンセル済み（400）
PATCH http://localhost:3000/api/reservations/58/cancel
Authorization: Bearer {{token}}

### 文字列を渡す(400)
PATCH http://localhost:3000/api/reservations/a/cancel
Authorization: Bearer {{token}}